name: Package
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  commit-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          message: 📦️ build for ${{ github.sha }}
